### ISSUE TITLE
Button colours are wrong since theming

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#1020]
![image](https://cloud.githubusercontent.com/assets/246103/10360164/95ee9f82-6d96-11e5-9f01-7633a4ddf930.png)

The text on the button should be white?

**Comment by billmn** [comment]
This is caused by style override of .btn-success:
https://github.com/cachethq/Cachet/blob/6b362fd88de44328d52a6c1016574a4487c350f0/resources/views/partials/stylesheet.blade.php

It could be enough to set the color attribute (#fff).

Can you clarify why you use **!important** for every of this styles?

**Comment by jbrooksuk** [comment]
> Can you clarify why you use !important for every of this styles?

I've got a feeling when I started it, none of the styles were updating.
