### ISSUE TITLE
Bad translation of ordinals in dates

### ISSUE THREAD

**Issue by rafoo** [cachethq/Cachet#1079]
The translation of dates in french (I have not tested other languages) keeps the english ordinals (1st, 2nd, 3rd etc...).

For example, in french, today's date is "jeudi 29 octobre 2015" but "jeudi 29th octobre 2015" is displayed instead.

**Comment by jbrooksuk** [comment]
@rafoo what version are you on? I think @joecohens and I looked into fixing this for V2?

**Comment by rafoo** [comment]
I don't know, I have seen this error on both the Framasoft status page (https://status.framasoft.org/) and the Cachet demonstration page (https://demo.cachethq.io/).

Sorry for the noise if this has been fixed; I will try to install V2 to see if the problem is fixed.

**Comment by jbrooksuk** [comment]
If you're seeing it on the demo page, then this isn't fixed properly.

That said, you can go and change the date format in the Dashboard; https://demo.cachethq.io/dashboard/settings/localization

![image](https://cloud.githubusercontent.com/assets/246103/10906907/5115a680-821d-11e5-98a5-591e00c162e1.png)

This will fix it for you, since we're including the `th` automatically, you'll just need to edit it.

**Comment by rafoo** [comment]
Ok, thank you!
