### ISSUE TITLE
Add report issue feature

### ISSUE THREAD

**Issue by SamuelMoraesF** [cachethq/Cachet#170]
It can be an simple button with an field on settings page to set the link destination, or an form that open on a modal and send the message to email to admins.

I recommend the first option because some enterprises already have an page or email to report the issue.

**Comment by Jamesking56** [comment]
and an option to have this disabled if the user chooses :+1:

**Comment by jbrooksuk** [comment]
It'd be off by default, if we were to add this.

**Comment by jbrooksuk** [comment]
Ok, so I've thought about this feature and I'm reluctant to add it. Here is why:

1. It starts off with a simple form that emails the status page members.
2. Then it turns into wanting to have the dashboard show these issues.
3. Next we turn it into essentially a ticket system.
4. Now the status page part of Cachet is never worked on because we're looking after a behemoth of a project.

You could certainly add your email into the **About Us** section in the dashboard. Remember you can use Markdown, so you could add a link with the `mailto` scheme.
