### ISSUE TITLE
Laravel 5.3 validation fixes

### ISSUE THREAD

**Issue by GrahamCampbell** [CachetHQ/Cachet#1888]

**Comment by cmosguy** [comment]
@GrahamCampbell @jbrooksuk  I am thinking about working on this issue and doing a proper pull request.  Can you advise what is the proper branch and unit tests you need help with?  Is there a specific form validation that you need updated?

**Comment by jbrooksuk** [comment]
I would hold off in this. We're too active in the 2.4 branch which isn't Laravel 5.3 yet.

**Comment by GrahamCampbell** [comment]
This will likely happen in the branch currently named 2.5.

**Comment by cmosguy** [comment]
@GrahamCampbell @jbrooksuk I wanted to contribute something for hacktoberfest.  IS there an issue that you would recommend I work on or should I start working on this?  Also, I noticed there was no 2.4 branch.  Just curious what you would recommend here?  Is this worth my time to contribute here for Hactoberfest?

Also, if I did work on this, I am concerned about losing track on features you have in the 2.3 branch that would be compatible with the 2.4.  Not sure how to manage this.  

Also, I was thinking of starting out by getting this ran through the Laravel shift app to start the upgrade process.  Any thoughts here?

**Comment by jbrooksuk** [comment]
@cmosguy 2.4 is currently the default branch 😄 

>  IS there an issue that you would recommend I work on or should I start working on this?

Please take your pick, we're using the [`hacktoberfest`](https://github.com/CachetHQ/Cachet/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest) label, but please do take some issues in the [V2.4.0](https://github.com/CachetHQ/Cachet/milestone/25) milestone.

> Is this worth my time to contribute here for Hactoberfest?

Any PR you open will be counted towards your Hacktoberfest total and we'll do everything we can to get your changes merged in, so yeah, it's definitely worth it for a free t-shirt!

> Also, if I did work on this, I am concerned about losing track on features you have in the 2.3 branch that would be compatible with the 2.4. Not sure how to manage this.

v2.3 isn't gaining any new functionality, only bug fixes. If needs be, we will merge the 2.3 branch into 2.4 to keep it up to date. You don't need to worry about this.

> Also, I was thinking of starting out by getting this ran through the Laravel shift app to start the upgrade process. Any thoughts here?

I mean you can, but we use the Command Bus heavily (which was changed in 5.3), so you'll need to make sure that our `AltThree/Bus` package is updated as well, otherwise nothing will work. Ping @GrahamCampbell on this.

**Comment by jbrooksuk** [comment]
Closed by https://github.com/CachetHQ/Cachet/pull/2195
