### ISSUE TITLE
Make Status Page filterable per component

### ISSUE THREAD

**Issue by janrenz** [CachetHQ/Cachet#1999]
As the feeds and the badges can be user per component i guess it would be nice if we can have a url that would only display the status and incidents of a selected component, either by component name or maybe also via the tags.

**Comment by jbrooksuk** [comment]
I'm going to push this back a release.

**Comment by franzliedke** [comment]
@jbrooksuk Since we need this feature in order to use Cachet, I would like to implement this. Would you consider a MR for inclusion in 2.4.0 if I send it in time?

In any case, I would be happy if you could tell me what you would want this to look like? Just a new query parameter (or URL fragment) that gets applied in the `DashboardController`? Or also new interface elements in the dashboard that either allow filtering, or at least show that we are currently filtering by a component? Anything else?

**Comment by jbrooksuk** [comment]
@franzliedke potentially... we really need to finish off #2325 though.

**Comment by franzliedke** [comment]
@jbrooksuk Thanks. Can you also comment on the second part of my question?

How about only adding the filter to the controller for now, and pushing interface changes (i.e. exposing it through the interface) to a later release? That would solve our problems, and prevent any conflicts with #2325...

**Comment by jbrooksuk** [comment]
Yeah, if we have the code in place to do that sure. Accepting a PR :)

**Comment by franzliedke** [comment]
I gave this a first try today, and it turns out things are a little bit more complicated than I thought.

The components (and their groups) are not loaded in the `StatusPageController`, but instead are loaded through a bunch of view composers, finally arriving in the `ComponentsComposer`. When filtering by component (or, rather, the component group), other "modules" will be affected as well, though. Which would be easier to achieve if the data was loaded in the controller.

@jbrooksuk How would you want me to achieve this? I will obviously have to evaluate the request parameter in the controller, but how should I pass it on to the view composers?

**Comment by jbrooksuk** [comment]
I'm unsure currently @franzliedke 😕

@joecohens @ConnorVG any ideas?

**Comment by franzliedke** [comment]
@jbrooksuk Well, to be honest, I was waiting for input from your guys' side. :wink:

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
