### ISSUE TITLE
Missing Component Status Language Line

### ISSUE THREAD

**Issue by johnwheal** [CachetHQ/Cachet#2020]
`cachet.components.status.0` is missing from the English language files. I'm not sure what the text should be - possibly "coming soon".

**Comment by jbrooksuk** [comment]
There [isn't a status](https://github.com/CachetHQ/Cachet/blob/2.3/app/Presenters/ComponentPresenter.php#L32) of `0`. You should never be able to get a status of `0`, although due to a bug in the dashboard this was possible for a short time.

We'll be making a patch release in the next couple of days (if not today) which fixes this issue :)
