### ISSUE TITLE
Question about base features (Is it only up/down monitoring?)

### ISSUE THREAD

**Issue by ScottBeeson** [CachetHQ/Cachet#2029]
I'm currently using Overseer and looking for a replacement.  I need to find a solution where I can perform a SQL query and create an alarm based on the results.  Perhaps as simple as if the result count is > 0.

Does Cachet have this ability?

**Comment by jbrooksuk** [comment]
Hey @ScottBeeson,

Cachet itself doesn't have this feature. We don't do monitoring because we recognised that it's a harder problem than people think, so we leave it to the experts!

That said, there is [Pingometer](https://pingometer.com) which you can signup for and then have update your Cachet status page :)

If you're looking for something self-hosted, you can use [cachet-monitor]https://github.com/castawaylabs/cachet-monitor) which also integrates into Cachet.

Hope that helps!
