### ISSUE TITLE
One Click / Easy Install

### ISSUE THREAD

**Issue by RyunUK** [CachetHQ/Cachet#2073]
Just wondering if any "One Click" Install / Easy Install was created? Noticed it was mentioned for V1 originally? Just thinking it could benefit additional users in the future?

**Comment by jbrooksuk** [comment]
We used to support Heroku's one-click deploy system, but it was removed when they changed their pricing.

It's _very_ unlikely we'll re-introduce any kind of one-click deploy system due to the fact that there isn't one system like Heroku, that isn't Heroku that is widely used.

Also, a Cachet [installation](https://docs.cachethq.io/docs/installing-cachet) is pretty simple.
