### ISSUE TITLE
"Some systems are experiencing issues" despite all operational

### ISSUE THREAD

**Issue by TheEpTic** [CachetHQ/Cachet#2241]
So I'm running 2.4.0-DEV and found this issue:

http://i.imgur.com/9NTVDq3.png

I can't seem to find anything to change it, so I'm guessing it's an internal bug at this point.
Our page: https://status.gota.io/

**Comment by jbrooksuk** [comment]
Since you're running v2.4-dev do you have any incidents with no fixed updates?

**Comment by TheEpTic** [comment]
Where could I check for this?

**Comment by jbrooksuk** [comment]
Well, I assume that you've upgraded from v2.3?

**Comment by TheEpTic** [comment]
Yes, sir.

**Comment by jbrooksuk** [comment]
Right, so the issue here (and for anyone else upgrading to v2.4) is that when you have reported incidents pre-v2.4 they're left in a non-fixed state. Cachet uses these "non-fixed" issues to calculate the status.

I don't know what the best thing to do here is now though... What do we do for people upgrading from v2.4? Perhaps we change how we calculate the status not to include incidents, and only go on Components?

**Comment by jbrooksuk** [comment]
Ping @CachetHQ/core and @ConnorVG for thoughts on this.

**Comment by jbrooksuk** [comment]
Technically, this isn't a bug, I just don't know how to account for previous incidents. We can't change the status on them all because people create multiple incidents.

**Comment by yuvarajan1989k** [comment]
Scenario:-

Components: Green
Compoenents_group: Green

Under past Incident section:-

there are 2 incident created:-

1 incident was in failing state
another incident was resolved.
(Note: Both incidents related to the same service.)
Dashboard status:-
Showing Issues but Everything is Operational

is it possible to display status on the dashboard based on component and component_group, instead of incidents?

**Comment by chreck** [comment]
To remove the "Some systems are experiencing issues" message you do the following steps:

1. Connect to your database with `mysql -h localhost -P 3306 -u cachet -D cachet -p`
2. Select the DB 

`USE cachet;`

3. Check the non fixed (FIXED = 4) incidents: 

`SELECT id, component_id, status, name, visible, occurred_at FROM incidents WHERE status != 4;`

4. Delete the incidents if you do not need them anymore: 

`DELETE FROM incidents WHERE status != 4;`

5. `exit;` mysql shell

**Comment by djgalloway** [comment]
An alternative to deleting all incidents that aren't "Fixed," one could just "Fix" them all with:

`UPDATE incidents SET status = 4 WHERE status != 4;`

Would recommend a `mysqldump -u cachet -p cachet > pre_update.sql` first.
