### ISSUE TITLE
unable to remove custom header

### ISSUE THREAD

**Issue by abioneperhobby** [CachetHQ/Cachet#2250]
in some older release, i maybe set "asd" asd custom header in order to understand if header saving works or not. 

some months ago, i updated cachet to the last release version 2.3.10

when i open the dashboard, i see "asd" as header.

if i try to remove the header, nothing occur.

in the screenshot you can see that i update "asd" to "asd1" and the data was posted to /settings,

but nothing changed.

![image](https://cloud.githubusercontent.com/assets/2149815/20483939/1d3b0178-aff5-11e6-97ee-42b5700df94e.png)

**Comment by jbrooksuk** [comment]
@abioneperhobby it looks like you need to make sure that `./bootstrap/cache{,t}/*` is writeable by your server process.

**Comment by abioneperhobby** [comment]
@jbrooksuk 

i run 

` chmod -R 777 bootstrap/`

but nothing changed :(

**Comment by Raphyyy** [comment]
This issue is still present to me with 2.4
I can set custom header but I can not remove it.
If you leave it empty and click on Save, it kept the previous value.
If you leave a blank space and click on Save, then there is a blank space saved as a custom header.
There is no way to remove it, in order to get back to the original header (banner image).
