### ISSUE TITLE
Email Sending Delay

### ISSUE THREAD

**Issue by Moogleson86** [CachetHQ/Cachet#2485]
Good morning,

I have an issue with email not being sent quickly. I have over an hour delay in email sending from our instance.

Any ideas or thoughts on a possible cause? I can provide any data needed.

Thanks

**Comment by jbrooksuk** [comment]
What queue driver are you using? What's your `crontab -e` output look like?

**Comment by Moogleson86** [comment]
Thanks for the reply,

The queue driver is as follows:
QUEUE_DRIVER=database

Also, the crontab -e is below:
* * * * * php /var/www/Cachet/artisan schedule:run >> /dev/null 2>&1

Thanks

**Comment by jbrooksuk** [comment]
Ping @GrahamCampbell I can't see anything obvious here. Any reason why mail would take so long?

**Comment by gerardgoubert** [comment]
As a note to the above issue (I am working with the reporter of this issue) -- emails that are first subscribed to the list (myself being the admin, aka position '0' in the list) get the email right away, but then the php/artisan seems to work through/down the list/queue... only sending once email at a time... and so I have another email account lower down the list (approx subscriber #70 out of 77) and it takes 35-85mins for the email to come to that email account, I have tcpdump'd smtp leaving the cachet server(s) and can see it sends only one email at a time and only one email every few minutes. Why does the code not send all the emails in one batch job (see issue 2462) -- as in issue 2462 we propose removing the "manage subscription" link in the emails and inserting a link to the incident itself -- this would make the email sent to each subscriber identical, and thus could be sent in bulk....anyway back to this issue: we have 77 subscribers (also just listing the subscriber list takes a while in the UI). There really is no use for email if the system cannot send out the emails within an minute of the incident happening... if users are notified of an incident after several hours, or even after the incident has already been resolved, this really makes a mess and confuses people.

**Comment by jbrooksuk** [comment]
Ah, it could be that the `database` driver is a bit slower. Are you able to use something like Redis?

**Comment by GrahamCampbell** [comment]
It's because you only have one queue worker. Try setting up 16 of them.

**Comment by GrahamCampbell** [comment]
If it's only sending one a minute, it means your queue is not set up correctly, and it's only the cron which is actually processing the jobs.

**Comment by gerardgoubert** [comment]
I believe we found the issue (we are still testing but looks promising)... problem was reading the config docs too literally ;-)
By following the docs for the supervisor setup, of the cachet.conf file it shows to use the username of "cachet" but after researching the supervisor docs, this need to be a valid system user with privileges to interact with the webserver. since there is no user 'cachet' in the system supervisor was throwing errors, once this was changed to 'www-data' and supervisor restarted, emails started to flow as expected.
We did not need to adjust the queue workers nor use redis. I also remove the cron job and supervisor is handle everything fins at this time. -- perhaps should only add a note to the install/config docs about in cachet.conf, "..use the username of the webserver process like www-data or apache depending on your system..." (not sure when the cachet username would ever work, unless you have a special setup where the cachet user is (1) created, and (2) in the www-data group??)
