### ISSUE TITLE
Add timezone to dates returned via the API

### ISSUE THREAD

**Issue by vitorbaptista** [CachetHQ/Cachet#2691]
The current dates are returned as `2017-08-24 13:23:48`, so we need to know the system's timezone to be able to fully identify this timestamp. It would be very useful if the timezone was part of the date strings.

My use case is that I'm trying to set up integration between CachetHQ and UptimeRobot. I want to be able to run the script that copies data from UptimeRobot multiple times, without creating new metric points after each run (i.e. it'll be idempotent). This mean that I need a way to identify which metric points weren't added yet. The ideal would be to have a consistent id shared by UptimeRobot and CachetHQ, but as that isn't currently possible, the workaround is to only submit points with a timestamp that isn't in CachetHQ yet. This has the obvious drawback that it'll ignore multiple metric points with the same timestamp, but that's unlikely in my case as the interval is 1~5 minutes.

**Comment by jbrooksuk** [comment]
@joecohens what do you think about this? Would we not need to migrate existing data to change the timestamps to timestampTz? Ping @GrahamCampbell

**Comment by bjoernffm** [comment]
I had this issue some time ago and found a solution to store the datetime within the tables independently from the servers timezone running the app. UTC is a good solution for that.

```php
$created = new DateTime(); // initialize class with local time
$created->setTimezone(new DateTimeZone('UTC')); // recaculate to UTC
$created = $created->format('Y-m-d H:i:s');  // would be 2017-08-24 13:23:48 based on UTC
```

When established, the tables are filled with consistent UTC-only-dates and it's quite easy to return that including a timezone:

```php
$dateTimeClass = new DateTime($originalDbDateTime, new DateTimeZone('UTC'));
$finalDateTime = $dateTimeClass->format('c'); // 'c' represents the ISO 8601 date
// 2017-08-24T13:23:48+00:00 includes the timezone (+-0 in UTC)
```

Since ISO 8601 is standardized, many libs (e.g. angularJs) are able to directly parse it and show the correct local time based on the users location.

With this solution it's also possible to write a script that updates all the old values in the tables.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
