### ISSUE TITLE
no possibility to subscribe notifications

### ISSUE THREAD

**Issue by paulo-decarvalho** [CachetHQ/Cachet#2745]
Hi,

I have activated the option to allow subscibers.

![image](https://user-images.githubusercontent.com/31652387/31074214-d684874a-a76f-11e7-82dd-8f8211aa8f95.png)

Unfortunately, in the status page, I see nothing that gives the possibility to subscribe.

How does it works ?

many thanks.

**Comment by paulo-decarvalho** [comment]
After reading more carrefully documentation and make some other tries, finnally I succeed in making the "subscribe" button appear.

Great functionnality. 

Many thanks !

**Comment by jbrooksuk** [comment]
:)

**Comment by getvivekv** [comment]
How did you enable it?

**Comment by getvivekv** [comment]
Also is there any documentation other than this page https://docs.cachethq.io/reference that I am missing?

**Comment by jbrooksuk** [comment]
Make sure you’ve configured the email settings in the .env file and enabled the setting in the dashboard.

**Comment by paulo-dc** [comment]
yes I had to set ALL parameters and enable it on dashboard .

For user/pass if not needed, "null" can work
MAIL_USERNAME=null
MAIL_PASSWORD=null

But, the first time the button didn't apper because I leave the parameter MAIL_NAME empty .
If this parameter is empty, the button do not appear.

So by putting something in, the button appear finally.
like:
MAIL_NAME="My Status Page"
