### ISSUE TITLE
Email confirmation URL should require interaction

### ISSUE THREAD

**Issue by hatclub** [CachetHQ/Cachet#2900]
v2.3.13 

Just following the link in the verify email is enough to subscribe someone, some mail scanning systems will follow links as standard to look for suspect content causing the address to become verified.

Cachet should, IMO, require the user to interact with the page to actually confirm their subscription.

**Comment by anthonybocci** [comment]
Hello,
I receive many email from many websites and the subscription pages never ask me any confirmation. Even when I register on a website, I have to click on a link in an email. This link doesn't have any confirmation.
Though, it would be possible to add a confirmation. Otherwise, perhaps there is a standard for these mail scanning systems and if so they may have a standardized user-agent like many bots.

**Comment by jbrooksuk** [comment]
@hatclub what does StatusPage.io do? I'm sure that previously this wasn't the case for them either. I'm also keen on as little friction as possible.

**Comment by jbrooksuk** [comment]
This will be fixed in https://github.com/CachetHQ/Cachet/issues/3102
