### ISSUE TITLE
Implementing SSO with SAML

### ISSUE THREAD

**Issue by nalysius** [CachetHQ/Cachet#2930]
Hi,
More and more companies are using Cachet as their status page.
Many companies have an SSO Identity Provider (IdP) to manage their employees and it may be tedious for them to create an account manually (or using API) into the Cachet database.
Implementing SSO as a Service Provider (SP) using SAML in Cachet would be a great help for them and would also help companies to adopt Cachet.

I am interested by implementing SSO in Cachet so I open this issue as an open discussion for guidelines, advices or anything.
A [PHP library](https://github.com/onelogin/php-saml) manages the SAML part.
I imagine that a company could configure some IdP in their Cachet instance and so on the login page we'd list all the configured IdP.

I'm open to all remark.

**Comment by jbrooksuk** [comment]
I'd be happy to support SSO, but I've no means of testing this. If someone wants to pick that up, that'd be great!

**Comment by anthonybocci** [comment]
The users may be stored in an Identity Provider (IdP) or in the Cachet's database. On the login page we can choose either to login using the form or one of the configured IdP.
On its first login using an IdP, the user is created into the database but this process is hidden (no email sent). This account is only used to create components, incidents, and so on. The user will not know the account is effectively created into Cachet.

The SSO would be `SP initiated`.

A second step would be to support SLO (Single Log Out) in order to log out the user if he is logged out from its IdP.

During development:
- [Saml-ipd][1] is a good IdP for development only
- [Shibboleth][2] is a great IdP

I suggest to install locally one IdP (saml-idp is really easy to use), use the [one login][3]'s library to handle SAML, and begin the configuration of the IdP listed on the login page before handling SAML.

If you're ok with that I'd begin with that.

[1]: https://github.com/mcguinness/saml-idp
[2]: https://www.shibboleth.net
[3]: https://github.com/onelogin/php-saml

**Comment by pitbulk** [comment]
Hi, php-saml maintainer here.
Let me know if you have any doubt with the SAML toolkit or how to do the integration.

Best regards.

**Comment by anthonybocci** [comment]
@pitbulk It seems the php-saml library requires the mcrypt extension, but this extension is removed in PHP 7.2.
Is there any plan to change that? I really like this library because if its ease to use, but this point blocks me.

**Comment by pitbulk** [comment]
branch 3.0.0 is compatible with PHP 7.2

**Comment by anthonybocci** [comment]
Great! Thanks for this information @pitbulk . Is this branch stable enough to be used in production?

**Comment by anthonybocci** [comment]
I've installed an Identity Provider (SimpleSamlPhp) on my local machine, but I wait for the roadmap (#2943) to know if it's a priority or not.

**Comment by jbrooksuk** [comment]
@anthonybocci we should definitely make SSO part of the 3.0 release. If we're smart, we could allow GitHub, Twitter, Facebook login etc.

**Comment by MarPiRK** [comment]
SSO for GitHub, Twitter, etc is based on OAuth2 (OpenID Connect in particular), so it's using different mechanism than SAML. Anyways OIDC support would be great too.

**Comment by jbrooksuk** [comment]
Per #2108 maybe we should open a single issue for improved authentication mechanisms?

**Comment by anthonybocci** [comment]
@jbrooksuk I think the common issue you are speaking about could be about a user/login modification in order to be as flexible as possible. But as what I read in #2108, the authentication logics are really different so it would be hard to manage all in one issue.
We could imagine first a kind of "login plugin" logic, and we implement this logic for every "plugin" or class. Cachet's controller would call the "login plugin" that was selected, and has no real idea about if it's a database, SAML, OIDC or LDAP. Once this logic is ready, done, tested, future-proof and implemented for the database, we could implement as many SSO as we want.

**Comment by titansmc** [comment]
Hi,
I would like to know if this is a work in progress or it is stacked somehow.

**Comment by jbrooksuk** [comment]
This is in the pipeline :)

**Comment by anthonybocci** [comment]
Hi @titansmc, I'm still there and still available to implement SSO/SAMLV2, but the work hasn't begin on this point yet.  
We are doing some stuffs on Cachet before, like working on documentation, making it more robust and so on. When we'll be ready, I'll begin the work on SSO.

**Comment by steffjenl** [comment]
@jbrooksuk @anthonybocci  Will Laravel's Sociallite not be a better solution? Then you have the most SSO providers at once.

https://laravel.com/docs/5.4/socialite
https://socialiteproviders.github.io/
https://github.com/SocialiteProviders/Providers/tree/master/src

**Comment by anthonybocci** [comment]
@steffjenl Thank you for your contribution, it's an interesting idea!  
I had in idea that companies will use an internal Identity Provider to manage their users. Why a company would allow anybody on Twitter or other to create an account on their status page?

May we use Sociallite and add a custom manager in order to manage their internal Identity Provider?

**Comment by steffjenl** [comment]
@anthonybocci sorry for my late answer. It is not only Twitter or other socialnetworks.

- Microsoft Azure (Office 365)
- GitHub
- GitLab (https://github.com/SocialiteProviders/Providers/tree/master/src/GitLab)
- Zenddesk
- Jira (https://github.com/SocialiteProviders/Providers/tree/master/src/Jira)
- Google
- Bitbucket

Most company's use Microsoft Office 365 or Google products for e-mail and Jira orZendesk for ticket system (dev/support) or GitLab, GitHub or Bitbucket for version control. 

And if that is not enough, you can always make your own socialite provider.

**Comment by jbrooksuk** [comment]
Socialite would be a good solution. I've used it at work with Azure previously. It doesn't solve the SAML issue though...

**Comment by steffjenl** [comment]
@jbrooksuk 
According to you, what software do companies use SAML as an Identity Provider? Microsoft Active Directory using ADFS for SAML and OAuth.

Is it a good idea if I create a test environment with ADFS with OAuth and a creating an Socialite provider?

**Comment by jbrooksuk** [comment]
@steffjenl I'm unsure to be honest, but @anthonybocci opened an issue regarding it, so people must use it?

**Comment by jbrooksuk** [comment]
I think we need to be careful that we don't support too many providers and make it confusing.

**Comment by steffjenl** [comment]
@jbrooksuk I completely agree!

**Comment by anthonybocci** [comment]
@steffjenl I like the idea, using this package to manage many providers is really interesting. That was not how I imagined the issue so I'll try to explain a bit more and tell me what you think.

People may be using things like Microsoft Azure, Saleforce of what ever they want. I didn't think about supporting one or an other Identity Provider. I did think about being a generic Service Provider.  
So according to me it's easier to support SAMLV2, have a configuration about signature/encryption etc, and allow our users to configure any Identity Provider. It's only about SAMLV2 so it may be Microsoft of other, it's the same.  
This way, we can avoid to _claim_ the support of many providers. We would be only a Service Provider that they can configure.

**Comment by jbrooksuk** [comment]
That’s be decent, but it would mean that people need to install other socialite providers if they need them. Is that ideal? They do require code changes.

**Comment by preetpal13** [comment]
Hey Guys
Is there an ETA for this feature

Thanks

**Comment by anthonybocci** [comment]
Hi @preetpal13,
There is no ETA now because it remains lot to do. In an other project I'm implementing SAMLV2 in Symfony 4.1 so I'm still excited by this subject. But before working on SSO in Cachet there are some things to do, like make it more stable, work on security, GPRD and so on. The roadmap already says that I think, so we follow it :)

**Comment by spencerryan** [comment]
+1 for SAML. We want to roll this out internally with Okta as our IdP. I'm happy to help with any testing you need once it gets to that point.

**Comment by anthonybocci** [comment]
@jbrooksuk Yes it seems to be good, it allows to use OneLogin, SimpleSamlPhp or other to manage the authentication. It avoids to implement SAML2 within Cachet.

**Comment by jbrooksuk** [comment]
@anthonybocci that’s great! Is anyone able to test it for us? :)

**Comment by anthonybocci** [comment]
@jbrooksuk I think to test it we have to install a local version of [simplesamlphp][1] and configure it. I've never used the REMOTE_USER, but I think anyone using it would be able to test that :)

[1]: https://simplesamlphp.org/samlidp

**Comment by dudeisbrendan03** [comment]
Was SAML SSO ever implemented

**Comment by rhysjtevans** [comment]
We would much rather OAuth/OIDC

**Comment by dudeisbrendan03** [comment]
> We would much rather OAuth/OIDC

SAML is utilised more often inside enterprise environments compared to OAuth

**Comment by spencerryan** [comment]
Indeed, while support for both would be great, if you're going to prioritize one it should be SAML. OAuth is shockingly rare inside enterprise.

**Comment by mysiki** [comment]
some news ? :)

**Comment by sama8** [comment]
If relevant -> [SAML Jackson](https://github.com/boxyhq/jackson)

**Comment by yoramshai** [comment]
any update on this?  :)

**Comment by steffjenl** [comment]
> any update on this? :)

I think this project is dead, the author is not responding.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
