### ISSUE TITLE
Totally blank page after upgrading from PHP 7.0 to 7.2

### ISSUE THREAD

**Issue by Daniel15** [CachetHQ/Cachet#3009]
After upgrading to PHP 7.2, Cachet was just returning a blank page. No error message, nothing under `storage/logs`. I switched Cachet back to PHP 7.0 and it started working again.

Any ideas on how to debug this?

**Comment by uxen-ab** [comment]
If you are on a development machine, update your `php.ini`in order to set `error_reporting` to `E_ALL` and `display_errors` to `1`. Otherwise, do this manyally in `public/index.php` using `error_reporting(E_ALL); ini_set('display_errors', 1)`. This will make PHP displaying the errors.
Also, you can check in `storage/logs/`, it's possible that the error has been logged.

We are a community on Slack and we'd be glad to help you! Please come on Slack (https://cachethq-slack.herokuapp.com) before opening an issue. We prefer keeping issues for bug and feature requests.

**Comment by Daniel15** [comment]
I found the error message in my php-fpm log:
```
"PHP message: PHP Fatal error:  Uncaught ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/status.yarnpkg.com/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php:51
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/status...', 51, Array)
#1 /var/www/status.yarnpkg.com/vendor/graham-campbell/exceptions/src/ExceptionIdentifier.php(51): count(NULL)
#2 /var/www/status.yarnpkg.com/vendor/graham-campbell/exceptions/src/ExceptionHandlerTrait.php(47): GrahamCampbell\Exceptions\ExceptionIdentifier->identify(Object(ErrorException))
#3 /var/www/status.yarnpkg.com/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): GrahamCampbell\Exceptions\ExceptionHandler->report(Object(ErrorException))
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(ErrorException))
#5 {main
```

This looks like a duplicate of #2862, so I'll close it out.
