### ISSUE TITLE
Cachet Suggestions

### ISSUE THREAD

**Issue by mattfleaydaly** [CachetHQ/Cachet#3025]
Hey there i've got a few suggestions!
Apologies if these have already been made.

1: The ability to assign Maintenance to a component. That way users more specifically know which component is affected.

2: The ability to set an end time on an incident. After that time hits, the incident should automatically be marked as resolved. This is good for managing incidents better.

3: Client side form to report an incident. Simple yet would be a massive help.

Thanks!

**Comment by jbrooksuk** [comment]
Hi @mattfleaydaly, thanks for reaching out. I hope I can answer all of your questions 😄 

1. This is addressed in https://github.com/CachetHQ/Cachet/issues/1176
2. I don't know how I feel about this. Maybe start a conversation in #1176 to see how other people think about it also? I'm not keen because IMHO you should be responsible for the issues. You could use the API though.
3. This is outside the scope of Cachet :)
