### ISSUE TITLE
Newsletter-Abonnement Update Mail-Problem

### ISSUE THREAD

**Issue by MichaelOrtnerINFO** [CachetHQ/Cachet#3514]
Hello, if I move every single component, then I get an update email. This is a bit stupid and spammed the mailbox too. Can you fix it? 

If you move the components in the dashboard as admin, then this update notifications comes.

**Comment by c0ri** [comment]
I had this issue too.
Please check my thread for solution:
Re-arranging components in list triggers email flood #3518

**Comment by MichaelOrtnerINFO** [comment]
Do you use docker? We use Docker and there is the problem. I just testing the normal installation now....

**Comment by c0ri** [comment]
@MichaelOrtnerINFO No docker installed here. I can't see what that has to do with it TBH. This is a very poor implementation of message handling if you ask me. I have 50+ users and each even moving a component to another location in the list (drag up and down) will generate a new email to each of those 50 people for each position it moved up in the list. I had thousands of emails stacked up quick. Moreover, it doesn't use any kind of message threading so it just sends one email at a time about once every 3-4 seconds.. that's just not scaleable.  I wish I had the time to work on this myself. I'd also want to put some API into Spark/Webex Teams and Slack to send rooms messages since no one really uses email these days anyway.

**Comment by MichaelOrtnerINFO** [comment]
Okay thats not the best. hmm. i hope that @jbrooksuk can fix this problem/feature. We don't need so many mails if we drag them up and down and this on a newsletter....

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
