### ISSUE TITLE
OAuth 2.0

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/Cachet#356]
Supporting OAuth 2.0 for the API would be a cool integration, but potentially needless at the moment?

**Comment by imbushuo** [comment]
Just tried to add [OpenID Connect](https://github.com/imbushuo/Cachet/tree/federated2.4) (similar to OAuth2) to Cachet. Currently it only works with Azure AD (because it depends on specific attributes like User Principal Name in order to distinguish users).

It doesn't break the current user system - I just extended several attributes to the user table. If registered user with the same user principal name provided by Identity Provider is found, just logs the user in. If not, sign up new user using the given claims. Almost everything is done in Controller level.

More cleanup and additional features have to be done - these federated users should not be allowed to modify some attributes like local password (also should not have the ability to log in locally via Cachet's `/auth/login`) and an explanation like _"Your account details is managed by your domain administrator"_ is required. And generalization - make sure it works with major identity providers, not only Azure AD.

The workflow works the same for SAML2 - I will see if I can add it later and send a PR.

![OpenID Connect Demo](https://ibwordpressimage.s3.amazonaws.com/Snippets/Moegirlpedia/AADLoginDemo.PNG)
