### ISSUE TITLE
Metric points missing after 6 points or 3 boxes

### ISSUE THREAD

**Issue by RamennBowls** [CachetHQ/Cachet#3999]
Hi, I recently installed Cachet 2.4.0-dev, using PHP 7.2, MySQL databases, and file for the driver and queue (APC just stopped working and started giving me an error 500 after clearing the cache). This is all on Ubuntu 18.04.

Metrics is alright, and I've seen some issues with it that people have reported, but this one is odd. For some reason, when ever my Metric points go past the last three boxes (fourth box or more), they just disappear and go into a straight line?

I'm not sure what the issue is or how to fix it. If you have any ideas, please let me know. I've also attached an image of what it looks like.
![image](https://user-images.githubusercontent.com/28948494/80238011-93e7b700-8655-11ea-8888-7e818f1dd74e.png)

**Comment by nalysius** [comment]
Hi,
Metrics are (supposed to be) the reflection of the datas, so in theory it would mean that you have no datas for the given times. If you have no data for a given point it is set to the default value configured in the metric.
If you do have datas for these times and the straight line is anormal, could you upload your database so we can import it and try to reproduce/debug the problem?

**Comment by Romanthefrog10** [comment]
Hi Nalysius,
Yes I understand that, I'm using Cachet-Monitor (First one on the third parties page), and so it updates the metric data every minute, but when ever the points and time move across when it passes a minute, what ever gets into that fourth box or further just disappears and so it results in move of it just being a straight line.

Could I ask what parts of the database you would need, I don't really want to update the whole thing just encase I leak something like some key specific to my Cachet (I'm not actually sure fully how Cachet works, not sure if theres anything I should keep private in my Cachet Database).

**Comment by Romanthefrog10** [comment]
I'm currently using File for my Driver Cache and Queue Cache, for some reason after I cleared the cache, APC was acting up and causing an error 500, not entirely sure why but I thought I would tell you just encase.

Here's an image of my metric, and here's my metric and metric points tables, the reason why there are two of the same metric is because I recreated the same one to see if it was just that one acting up but no, it's happening to them all. [Metrics Tables.zip](https://github.com/CachetHQ/Cachet/files/4534999/Metrics.Tables.zip)
![image](https://user-images.githubusercontent.com/28948494/80303182-77a75f80-87a6-11ea-8c7a-dca3ededce41.png)

**Comment by nalysius** [comment]
Thank you @Romanthefrog10 I just imported your tables in my database. In the `metric_point` table the datas start the 2020-04-26 so it's normal that before this date your line is at 0. You just have no more data.

I saw something that could be a problem for you, your metrics are configured to display datas as "Sum". You are monitoring the response time of a daemon or something. If you monitore twice, the first time it might take 10ms and the second time it might take 20ms, it'd be interesting to have 15ms as the average instead of 30ms as the sum. That's why currently there is one point with its value of 150008ms.

**Comment by Romanthefrog10** [comment]
I think you may be misunderstanding or confused, the reason why it says it started on 2020-04-26, was because I reset the table to see if it would fix it. This is also why I had two monitors to see if it was just an issue with one.

Every minute, they metric moves across for the current minute, so it can do this it moves it across but for some reason they just disappear. Here's another image of the metric right now, you can see its moving across every minute, but at the fourth box the metric point just disappears and goes flat.
![image](https://user-images.githubusercontent.com/28948494/80307871-c4e5fa00-87c3-11ea-8412-a61fe9dd6689.png)

**Comment by Romanthefrog10** [comment]
If you look at the time stamps from the last image compared to this one, you can see those points are missing and are 0 again?
![image](https://user-images.githubusercontent.com/28948494/80308028-91f03600-87c4-11ea-9696-387af595453c.png)

**Comment by nalysius** [comment]
Ok I think I understand @Romanthefrog10. The problem is the disappearing of the datas. I will use a  _curl_ command to post datas into a metric every minute and try to reproduce it.

**Comment by nalysius** [comment]
I'm not able to reproduce your problem when different values are posted each time. @Romanthefrog10 could you try to run the Bash script I posted in the previous comment and see if it's able to reproduce the problem?

In my case I got this
![cachet-metrics](https://user-images.githubusercontent.com/7780244/80661097-f396f580-8a8d-11ea-9210-22ac2b59d469.png)
_Cachet metric_

**Comment by marek-knappe** [comment]
The fix for me was changing the postgresql timezone to be the same as timezone in cachet

**Comment by Romanthefrog10** [comment]
Hi Marek, as Cachet uses UTC and not the specified time zone in some instances, me being in the UK and it being BST right now caused a load of issues. After changing some time zones, it appeared all working. But this problem I have reported, is still an issue and have contacted many other developers which are stumped. It's not an issue that can be reproduced easily, due to the way Cachet is made stuff like the Time zone could affect results..

**Comment by marek-knappe** [comment]
> Hi Marek, as Cachet uses UTC and not the specified time zone in some instances, me being in the UK and it being BST right now caused a load of issues, as some places like the UK don't always stick with one time zone, so it can change depending on what point we are into the year.
> 
> After changing some time zones, and making everything UTC to comply with Cachet, the metric being completely broken and many cachet functions started to all work. But this problem I have reported, is still an issue and have contacted many other developers which are stumped on what could be causing this issue.
> 
> It could very well be the 3rd Party monitoring tool I have, that I got off of the Cachet Documentations page but I need that to do what I need. Without making my own monitoring software for cachet, and all the other monitoring software for cachet being quite bad in my opinion, I won't be able to do what I need with the metrics. Considering the tool was last updated two years ago, posting the issue there would not be of much use.
> 
> It's not an issue that can be reproduced easily. Due to the way Cachet is made, stuff like the Time zone can affect results, reproducing the issue can be very hard and maybe near impossible as it may not even be cachet causing the issue. As far as I've tested, I get this issue on every machine with what ever I try.

Do you have it running now with the issue? Can you check my fix branch if that helps:
https://github.com/marek-knappe/Cachet/tree/fixing-issue-3842

This is very weird thing that is happening there - which is adding to timeframe, everytime it doesn't find correct values, in mine it caused in wrong timezone to be like yours, in correct timezone was like in the issue #3842

**Comment by Romanthefrog10** [comment]
> > Hi Marek, as Cachet uses UTC and not the specified time zone in some instances, me being in the UK and it being BST right now caused a load of issues, as some places like the UK don't always stick with one time zone, so it can change depending on what point we are into the year.
> > After changing some time zones, and making everything UTC to comply with Cachet, the metric being completely broken and many cachet functions started to all work. But this problem I have reported, is still an issue and have contacted many other developers which are stumped on what could be causing this issue.
> > It could very well be the 3rd Party monitoring tool I have, that I got off of the Cachet Documentations page but I need that to do what I need. Without making my own monitoring software for cachet, and all the other monitoring software for cachet being quite bad in my opinion, I won't be able to do what I need with the metrics. Considering the tool was last updated two years ago, posting the issue there would not be of much use.
> > It's not an issue that can be reproduced easily. Due to the way Cachet is made, stuff like the Time zone can affect results, reproducing the issue can be very hard and maybe near impossible as it may not even be cachet causing the issue. As far as I've tested, I get this issue on every machine with what ever I try.
> 
> Do you have it running now with the issue? Can you check my fix branch if that helps:
> https://github.com/marek-knappe/Cachet/tree/fixing-issue-3842
> 
> This is very weird thing that is happening there - which is adding to timeframe, everytime it doesn't find correct values, in mine it caused in wrong timezone to be like yours, in correct timezone was like in the issue #3842

I wanted a simple solution, and had just decided to set all my time zones (on System, PHP, etc) to UTC as I've seen many many others have the same issue with time zones. Having it specifically work with BST is not something I needed, it was a want not a need and I was kind of too lazy to fix.

I took the easy route, and because the time zones and metric times are not a big deal for me I've just set everything to UTC, that way it all works with Cachet, I do wish the time zone function within the cachet dashboard settings was affective, but saddly not.

**Comment by rsiebertdev** [comment]
Looking at this two years later... I do wanna apologize for my attitude, sorry! 😅
_Also closing this for being stale, and for the fact that I don't wanna see my own comments_
