### ISSUE TITLE
Click on "manage subscription" causes "invalid signature" issue

### ISSUE THREAD

**Issue by kcan** [CachetHQ/Cachet#4013]
![image](https://user-images.githubusercontent.com/3047481/81301078-deffc200-9078-11ea-91d5-dd7de825b7d9.png)
![image](https://user-images.githubusercontent.com/3047481/81301116-ed4dde00-9078-11ea-8508-9505a4ebd161.png)

**Comment by langemeijer** [comment]
This problem is introduced in commit 7f53a7e9dfdac8431a23d3d2a49727d4047f5685 when signed routes were introduced for subscribe/verify and subscribe/manage. @craigballinger fixed a few of the places where urls were created but left a few for me. I've fixed this locally and will submit a pull request that solves this issue later today.

**Comment by manfred-warta** [comment]
Hi everybody, sorry that i have to inform you, that this issue is present again in the docker version cachethq/docker:latest aka v2.4.0-dev

**Comment by riddlenl** [comment]
> Hi everybody, sorry that i have to inform you, that this issue is present again in the docker version cachethq/docker:latest aka v2.4.0-dev

I also see it indeed..

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
