### ISSUE TITLE
Email about MAINTENANCE

### ISSUE THREAD

**Issue by michael-yanov** [CachetHQ/Cachet#4120]
When I create a Maintenance I can receive it for my email, but body of the message is not displayed, I can see just the name of the maintenance. Is there a way to fix it?
![cachet](https://user-images.githubusercontent.com/55269826/93650151-66d9dd80-fa16-11ea-8a20-f62907106541.png)
![cachet2](https://user-images.githubusercontent.com/55269826/93650162-6fcaaf00-fa16-11ea-8954-18b3325d3d43.png)

**Comment by cp-sumi-k** [comment]
hey @michael-yanov , you can fix it by adding body  to email at https://github.com/CachetHQ/Cachet/blob/cfd173cf122d925b70d5133a37528db6120bea67/app/Notifications/Schedule/NewScheduleNotification.php#L70

Like below,

```
$body = trans('notifications.schedule.new.mail.body', [
            'message' => $this->schedule->message,
        ]);
```

and add `$body` in markDown 

Then pass body to `schedule` array at `https://github.com/CachetHQ/Cachet/tree/2.4/resources/lang/your-app-language/notifications.php` as,

`'body'    => ':message',`

And add {{$body}} [after this](https://github.com/CachetHQ/Cachet/blob/cfd173cf122d925b70d5133a37528db6120bea67/resources/views/notifications/schedule/new.blade.php#L4).

Hope its useful.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.

**Comment by frank42hh** [comment]
Hi,

I just stumbled upon the same problem. No email body in scheduled maintenance emails.

As far as I can see, the initial report happened in September 2020, e.g. more than 4 years ago. In August 2023 you stated that 2.x will no longer be supported. While I can understand the reasons behind this, I don't feel satisfied with that, because if you stop supporting an official release and concentrate on a new version that is NOT yet released, you make people feel irrelevant when you ignore a bug report for 3 years and then answer it with "is no longer supported".

Besides, https://docs.cachethq.io/v3.x/installation states:

```
Cachet v3.x is currently in development and not yet released. The following instructions are intended for development purposes only and are subject to change.
```

So, I don't think I will install this on a production service. But if you refuse to support your latest 2.x release, I tend to search for another software product that has better support.
