### ISSUE TITLE
cachet disable expand button

### ISSUE THREAD

**Issue by lazat77** [CachetHQ/Cachet#4191]
In the settings meny of cachet you can set  Expand/Collapse options in the component group. But if set only expand on errors you can still go to the dashbord and press (+) sign to expand the list of servers. Why?  I don't want to show all my servers if they are working fine, only servers that have a problem. Can I remove the (+) sign or even better not populate the webpage  if every thing is working? 

using 2.4.0-dev

**Comment by agopala-cachet** [comment]
I have the same problem. The problem is the "+" button is inactive, irrespective of the option you choose while configuring component groups. I think it is a compatibility issue. If the view is expanded, it stays that way. If it is collapsed by default it stays that way.
I did not see the problem with Ubuntu 14.0.8 / PHP 5.x. / Apache 2.0 / Cachethq 2.4.0-dev
I do see the issue with PHP 7.2.24-0ubuntu0.18.04.7 / Apache 2.4

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
