### ISSUE TITLE
Unable to scale beyond single node, random logouts, and incorrect selection of X-Forwarded-For IP

### ISSUE THREAD

**Issue by Matthew-Beckett** [cachethq/cachet#4268]
I am encountering an issue with Cachet running Kubernetes. 

The session store is populated with the IP of my upstream Nginx server, not of the requesting client, this is causing random logouts, failed submission of changes, and ultimately a deployment in which I cannot go HA with.

My deployment has L4 load balancer in front of my cluster and I am using cachet-docker as provided, when inspecting the session table, I can see that the IP populated for that session is that of the upstream Nginx Ingress Controller which send the request in my cluster, not that of the requesting client passed through via the load balancer to my Ingress Controller.

My externalTrafficPolicy for my LoadBalancer Service is Local as documented.

**Comment by pavog** [comment]
Hi, to me this doesn't sound like a problem from the application part of Cachet, but rather a problem with the Docker image or the underlying Laravel framework. Unfortunately I can't help you with that, but you might find some useful information on:
- The [CachetHQ/Docker](https://github.com/CachetHQ/Docker) GitHub repository
- The [Laravel documentation](https://laravel.com/) 
- Google or Stackoverflow when searching for Laravel (instead of Cachet) in kubernetes

**Comment by Matthew-Beckett** [comment]
This issue is not present in https://github.com/fiveai/Cachet/tree/v2.5.0, recommend utilising this fork for users experiencing the same behavior.
