### ISSUE TITLE
Fixed: Implement custom theme

### ISSUE THREAD

**Issue by ghost** [cachethq/cachet#4302]
Hi all, 
I am trying to implement this theme on my status page but no success I have applied the custom colours in theme, but anything else I can't.
[Link to theme(Cachet Material Dark)](https://userstyles.org/styles/155143/cachet-material-dark)

**Comment by pavog** [comment]
Hi, so I just tried both ways:

1. Adding the CSS code from the linked page. 
To do this, I inserted the code under .../dashboard/settings/stylesheet.
I removed the rule 
```css
@-moz-document domain("/*[[domain]]*/")
{
...
}
``` 
and it worked fine.

2. I set the colors in .../dashoard/settings/theme and it worked fine.

So I don't quite understand what your problem is?
Could you explain in more detail what is not working?

**Comment by ghost** [comment]
Hi, pavog.
Well yes, that works, I didn't knew I had to remove te moz-document rule, actually I did but I forgot the ending }.
So, thank you so much.

**Comment by pavog** [comment]
Great, glad I could help :)

**Comment by ghost** [comment]
Hi, pavog,
One more question, how do I get Cachet API token? 
Regards

**Comment by pavog** [comment]
Cachet API tokens are per user.
You can view the API  Token via the user profile. To do this, visit .../dashboard/user, click on a user and then on the API Token. You may have to regenerate the token.
