### ISSUE TITLE
Support for New relic

### ISSUE THREAD

**Issue by andrefrcastro** [cachethq/Cachet#579]
Graphs with metrics would be great, also system/app status could be updated automatically.

**Comment by jbrooksuk** [comment]
@andrefrcastro can you explain this a bit more please? :)

**Comment by andrefrcastro** [comment]
New relic provides metrics and important information on how the app is performing, such as response times (would be cool for graphs), error rates, alerts of downtime and other events, throughput, etc

**Comment by jbrooksuk** [comment]
Looks like Newrelic supports [webhooks](https://docs.newrelic.com/docs/alerts/alert-policies/examples/webhook-examples), is this something you can implement via that method?

**Comment by andrefrcastro** [comment]
I guess so. The API would also be helpful for the metrics such as response time: https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/new-relic-rest-api-v2-getting-started

Some demos: http://data-api-demo.newrelic.com/

**Comment by jbrooksuk** [comment]
This isn't something that Cachet will be doing for now, because we'd have to build a whole provider system for the API.

- Use web hooks to get some of the data out. I believe that you can set what data to send to the web hook, so this is your best bet.
- Setup some kind of proxy to get the data out of Newrelic into Cachet.

Perhaps in the future we'll do this, but not right now as it should be possible to get enough out currently :)
