### ISSUE TITLE
Install via apt-get

### ISSUE THREAD

**Issue by Jamesking56** [cachethq/Cachet#610]
Since you are no longer supporting Heroku (which mine is currently hosted with). I am going to setup Cachet on DigitalOcean.

It would be nice if I could spin up a droplet and then do a simple `apt-get install cachet` and Cachet can then install what it needs, pull from the Git repo etc.

The reasons for doing it this way are:

- Really really easy to install for people not too familiar with Linux
- Linux can manage updates for it as if it was a normal package
- Makes an easy replacement for a simple deploy button (giving a very simple guide for setup on DigitalOcean using Ubuntu servers).

What do you think?

**Comment by jbrooksuk** [comment]
I like the idea, although I've no idea how to set that up.

**Comment by itscassa** [comment]
@jbrooksuk https://wiki.debian.org/HowToPackageForDebian

**Comment by anarcat** [comment]
a debian package would be great, but unfortunately it would probably depend on packaging composer first, which is in process: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=714118

then laravel would need to be packaged.

then finally cachet would need to be packaged.

quite an undertaking, i just gave up and deploy from git. see https://wiki.koumbit.net/CachetConfiguration#First_install

**Comment by jbrooksuk** [comment]
@anarcat how come Laravel would need to be packaged? Surely the installer would just deal with installing Laravel via Composer. We wouldn't install the `laravel` command here, but the vendor directories.

**Comment by anarcat** [comment]
there's this thing called "convenience copies of code" in the Debian policy:

http://www.debian.org/doc/debian-policy/ch-source.html#s-embeddedfiles

it specifies that:

> Debian packages should not make use of these convenience copies unless the included package is explicitly intended to be used in this way.[29] If the included code is already in the Debian archive in the form of a library, the Debian packaging should ensure that binary packages reference the libraries already in Debian and the convenience copy is not used. If the included code is not already in Debian, it should be packaged separately as a prerequisite if possible.[30]

Notes 29 and 30 read:

> 29: For example, parts of the GNU build system work like this. [I think this refers to the traditionnal `./configure` scripts)
> 30: Having multiple copies of the same code in Debian is inefficient, often creates either static linking or shared library conflicts, and, most importantly, increases the difficulty of handling security vulnerabilities in the duplicated code.

The idea is that the "vendor directories" are shared copies of code that would eventually be used by multiple packages such as Cachet, and as such, it would be simpler to maintain it as its own package for the security team.

**Comment by ojdon** [comment]
Hi @Jamesking56 (Small world! Spoke to you at GradEX.)

Just to chip in, but isn't Ubuntu in a bit of 'limbo land' when it comes to getting packages in the main repo? I'm a little rusty when it comes to using Ubuntu but have tried to keep up with the latest news.

I mean, you could try and send it upstream to the Debian repo and then that'll be pulled down for the next Ubuntu release. There is also using PPAs, however it's going to need someone to take the time and effort to maintain the build process for each new release of Ubuntu.

Who's to say that PPAs/apt-get is going to be around for the next LTS release of Ubuntu Server? Considering Canonical are focusing on the development of their new Snappy package management system. 

It's probably something that should be considered and revisited in the future but not for the big 1.0.0 release of Cachet. Especially if the plan is to use the new Snappy package manager for the next LTS release of Ubuntu Server.

**Comment by Jamesking56** [comment]
@ojdon agreed, Ubuntu's package processes are a tad slow which could make this much harder to implement, I'm just thinking of the overall installation of the system as an apt-get package is very easy to install and manage in with other packages installed on a server.

Maybe there is another easy installer type thing we can utilise instead of apt-get, maybe some form of wizard?

**Comment by jbrooksuk** [comment]
Thanks for your insights @ojdon.

I'm unsure. If you're looking at setting up a status page, you're *probably* technically inclined and can go through setting up Apache/nginx, a database and then installing Composer and Cachet itself. If not, then we have instructions and there are tutorials available by other people, similar to Wordpress do it.

I personally don't have the time nor the patience to maintain a package or a PPA as well as Cachet itself. Perhaps in the future, yes and I'd support an unofficial PPA if someone was interested in doing so, but it won't be done by us for the foreseeable future, not least because of the package management situation.

**Comment by anarcat** [comment]
in my experience, cachet is an exception rather than the rule, and it was quite painful for me to go through all the manual steps to do the upgrade. it also doesn't explicitely have good ways of deploying upgrades itself - which we usually do through debian packages.

so yeah, i would say this is a limitation in Cachet right now. the fact that I am competent enough to configure a webserver, database, Composer, PHP, Laravel, Cachet and whatnot doesn't mean i enjoy doing that by hand at random untold moments.

debian packages fix that, as do other provisionning systems, but since there's no other, that's a good candidate as any.

**Comment by jbrooksuk** [comment]
In the future we will be implementing an upgrade system.

Please don't forget that Cachet is still beta and things like difficult upgrades are hard to avoid when first developing an app. In Version 2 we will make upgrades much easier.

**Comment by shaun-ba** [comment]
This would be far better for sure, the installation process was quite painful!

**Comment by jbrooksuk** [comment]
> This would be far better for sure, the installation process was quite painful!

What did you struggle with? At what point did the docs let you down at?
