### ISSUE TITLE
Improving Scheduled Maintenance

### ISSUE THREAD

**Issue by TheoBearman** [cachethq/Cachet#715]
I do not like how the scheduled maintenance is handled at present. Can I suggest a new way of handling it, much more like a timeline of events.

For example:

* I add scheduled maintenance to my Cachet install with a brief description. This is prior to the scheduled maintenance window.
* I then add updates as the maintenance is being carried out. For example, updating the issue when the maintenance has started and updating the issue as each section of the maintenance is completed.
* Updating the issue when the maintenance is completed with a time.

Here is an example of what I mean (hopefully it could be made to look a bit prettier):

![dws](https://cloud.githubusercontent.com/assets/6546590/8143843/968c403c-11b8-11e5-9dbd-2bd847ed2859.JPG)

In many ways this suggestion is very much like #530 but for maintenance as well as incidents.

I love Cachet but I think maintenance and issues are too closely linked at the moment. This is shown most clearly when Cachet says that `Some Systems Are Experiencing Issues` when maintenance begins. What if I'm just adding a feature as part of the maintenance which does not impact the performance of the website/infrastructure at all?

Thanks!

**Comment by jbrooksuk** [comment]
This is something that we are going to address in V2.

Currently the implementation of incidents, components and scheduled maintenance are stupid. In the next version they'll be completely re-written, allowing you to build up a story of exactly what happened during down time.

I can't share all of my ideas just yet, but here is an overview of the changes:

- Where you currently create an incident per-update, that'll change to one incident with "updates" added to it.
- Incidents will be able to affect multiple components, because it's quite possible to have :hankey: :facepunch: :dash: and make a mess of everything.
- Scheduled maintenance will be its own thing to allow for recurring updates and other things that I have planned.

# Disclaimer :wink: 

Remember that I originally based Cachet on StatusPage.io a product for myself that only needed to do A, B and C. Not only do I need a different implementation, but others too. I regret my original decision to recreate StatusPage because in my opinion they (and Cachet alike) do not do a good job at all.

**Comment by TheoBearman** [comment]
Sounds very interesting. Thanks for the comprehensive answer @jbrooksuk.

**Comment by jbrooksuk** [comment]
@TheoBearman not as of yet I'm afraid.

**Comment by TheoBearman** [comment]
@jbrooksuk Please let us know when there is one!

**Comment by bolshoy** [comment]
@jbrooksuk I can suggest to add a list of affected components to the scheduled maintenance, so incidents coming from these components are ignored/stashed.

**Comment by jbrooksuk** [comment]
Merged into https://github.com/cachethq/Cachet/issues/1176
