### ISSUE TITLE
Subscriber email documentation generating errors

### ISSUE THREAD

**Issue by LinHub** [cachethq/Cachet#860]
The environment is strictly default built by docker-compose with no alternations. It is all synced from GIT for the most up to date source.

root@a9a1886cd6d0:/var/www/html# php artisan schedule:run 1

                       
  [RuntimeException]   
  Too many arguments.  
                       
The cron command will not run. Once the cron is setup, the system does not send email. I can't find any clarity on how to get this working.

**Comment by LinHub** [comment]
It is taken from the page here:

https://cachet.readme.io/docs/setup-subscribers

I can run it without the 1 on the command line, but there is nothing specific about what the 1 is or if it is needed. I searched Google as well, but there is no documentation about the 1.

**Comment by jbrooksuk** [comment]
The example for setting up the cron is taken from http://laravel.com/docs/5.0/artisan#scheduling-artisan-commands

When you're calling `schedule:run` yourself, you should just do `php artisan schedule:run`.

**Comment by n0mer** [comment]
@LinHub 

problem here is that currently image on docker hub is built from "master" GitHub branch.

After 1.0 release some versioning started to appear (e.g. tag for 1.1 release, and dev-only version branched that are then merged to `master`). 

But this beauty is not yet reflected to Docker Hub.

I mean, once release is tagged on GitHub, then it would be great to create corresponding label on Docker Hub (otherwise there will be literally no way of using this tagged release in Docker world, rather than building image from sources by yourself).

And, since there is automated build already present on Docker Hub, it would be also great to create corresponding labels for at least "latest" (which is `master`), and (if time allows) to branches currently being under development. Currently this is 1.1 and 2.0.

**Comment by LinHub** [comment]
Let me try to be more specific since everyone seems to have missed the point.

The cron is not working. Email is not working. Email is not sending. No email leaves the server.

This cron is setup in crontab -e per the documentation. It does not work.



* * * * * php /path/to/artisan schedule:run 1>> /dev/null 2>&1

Running the following command sends email. Email leaves the server once this runs:

cd /var/www/html

php artisan schedule:run

The 1 in the cron command is not documented. I can't find any mention if it anywhere. Why is it there? Why is the cron not working? Why does it run correctly without the 1?

I hope that is clearer.

**Comment by n0mer** [comment]
you should change `php /path/to/artisan schedule:run` to `php /var/www/html schedule:run` in your crontab

**Comment by jbrooksuk** [comment]
> Let me try to be more specific since everyone seems to have missed the point.

It's possible that the docs are incorrect. I copied the command from Laravel's docs for consistency, but it could very well be wrong.

If removing the `1` resolves the issue, then you're likely correct. I'll adjust the docs.
